@echo off
echo Starting Achievement Vault...
echo Opening Chrome...
start chrome http://localhost:3000/
echo Waiting for Chrome to launch...
timeout /t 2 /nobreak
echo Starting server...
start cmd /k "cd /d %~dp0 && npx nodemon backend/server.js"
